#!/usr/bin/env python3
"""Generate compact GB18030 -> BMP lookup data using Python's canonical codec."""

from pathlib import Path

out = Path(__file__).resolve().parents[1] / "gb18030_table.h"

pairs = []
for lead in range(0x81, 0xFF):
    for trail in list(range(0x40, 0x7F)) + list(range(0x80, 0xFF)):
        raw = bytes((lead, trail))
        try:
            s = raw.decode("gb18030")
        except UnicodeDecodeError:
            continue
        if len(s) == 1 and ord(s) <= 0xFFFF:
            pairs.append(((lead << 8) | trail, ord(s)))

# Four-byte GB18030 pointers are mostly linear Unicode ranges. Discover the
# ranges from Python's standard codec and retain only BMP mappings, which is
# exactly what the calculator's UTF-16 graphics API can draw directly.
ranges = []
start_p = start_u = prev_p = prev_u = None
for p in range(126 * 10 * 126 * 10):
    b1 = p // (10 * 126 * 10) + 0x81
    rem = p % (10 * 126 * 10)
    b2 = rem // (126 * 10) + 0x30
    rem %= 126 * 10
    b3 = rem // 10 + 0x81
    b4 = rem % 10 + 0x30
    try:
        s = bytes((b1, b2, b3, b4)).decode("gb18030")
        u = ord(s) if len(s) == 1 and ord(s) <= 0xFFFF else None
    except UnicodeDecodeError:
        u = None
    if u is not None and prev_p is not None and p == prev_p + 1 and u == prev_u + 1:
        prev_p, prev_u = p, u
        continue
    if start_p is not None:
        ranges.append((start_p, prev_p, start_u))
    if u is None:
        start_p = start_u = prev_p = prev_u = None
    else:
        start_p = prev_p = p
        start_u = prev_u = u
if start_p is not None:
    ranges.append((start_p, prev_p, start_u))

with out.open("w", encoding="ascii") as f:
    f.write("/* Generated by tools/gen_gb18030.py. */\n")
    f.write("#ifndef NTEXTS_GB18030_TABLE_H\n#define NTEXTS_GB18030_TABLE_H\n")
    f.write("typedef struct { unsigned short key, value; } GbPair;\n")
    f.write("static const GbPair gb_pairs[] = {\n")
    for key, value in pairs:
        f.write(f"{{0x{key:04x},0x{value:04x}}},")
    f.write("\n};\n")
    f.write("typedef struct { unsigned start, end; unsigned short unicode; } GbRange;\n")
    f.write("static const GbRange gb_ranges[] = {\n")
    for start, end, value in ranges:
        f.write(f"{{{start}u,{end}u,0x{value:04x}}},")
    f.write("\n};\n#endif\n")

